TPAM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from TPAM.admin import CustomAdminSite

admin.site.__class__ = CustomAdminSite

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("", include("mainmenu.urls", namespace="mainmenu")),
    path("api/", include("api.urls", namespace="api")),
    path("users/", include("users.urls", namespace="users")),
    path("rtt/", include("rtt.urls", namespace="rtt")),
    path("locos/", include("locos.urls", namespace="locos")),
    path("companies/", include("companies.urls", namespace="companies")),
    path("notes/", include("notes.urls", namespace="notes")),
    path("brmsra/", include("brmsra.urls", namespace="brmsra")),
    path("people/", include("people.urls", namespace="people")),
    path("storymaps/", include("storymaps.urls", namespace="storymaps")),
    path("locations/", include("locations.urls", namespace="locations")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    SHOW_TOOLBAR_CALLBACK = True

api/urls.py
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'api'

urlpatterns = [
    path('register/', views.register),
    path('login/', views.login),
    # path('manufacturers/', views.Manufacturers.as_view(), name='manufacturers'),
    path('manufacturers/', views.manufacturers, name='manufacturers'),
    path('manufacturer/<int:pk>', views.manufacturer, name='manufacturer'),
    path('persons/', views.persons, name='persons'),
    ]

# To investigate:- Appears in https://www.django-rest-framework.org/tutorial/3-class-based-views/
# urlpatterns = format_suffix_patterns(urlpatterns)

locations/urls.py
from django.urls import path
from . import views

app_name = "locations"

urlpatterns = [
    path("", views.index, name="index"),
    path("routes_southern", views.routes_southern, name="routes_southern"),
    path("locations/", views.locations, name="locations"),
    path("location/<int:location_id>/", views.location, name="location"),
    path("location_area/<slug:slug>/", views.location_area, name="location_area"),
    path("routes/", views.routes, name="routes"),
    path("routes_timeline/", views.routes_timeline, name="routes_timeline"),
    path("route/<int:route_id>/", views.route, name="route"),
    path("route_storymap/<slug>/", views.route_storymap, name="route_storymap"),
    path("route_map/<slug>/", views.route_map, name="route_map"),
    path("route_timeline/<slug>/", views.route_timeline, name="route_timeline"),
    path(
        "closed_lines_region_select/",
        views.ClosedLinesRegionSelectView.as_view(),
        name="closed_lines_region_select",
    ),
    # path(
    #     "map_closed_lines/<str:geo_area>/",
    #     views.MapClosedLines.as_view(),
    #     name="map_closed_lines",
    # ),
    path("elrs/", views.elrs, name="elrs"),
    path("elr_map/<int:elr_id>/", views.elr_map, name="elr_map"),
    path("elr_storymap/<int:elr_id>/", views.elr_storymap, name="elr_storymap"),
    path("elr_history/<int:elr_id>/", views.elr_history, name="elr_history"),
    path(
        "elr_display_osmdata/<int:elr_id>/",
        views.elr_display_osmdata,
        name="elr_display_osmdata",
    ),
    path(
        "regional_map_select/",
        views.RegionalMapSelectView.as_view(),
        name="regional_map_select",
    ),
    path(
        "regional_map/<str:geo_area>/",
        views.regional_map,
        name="regional_map",
    ),
    path("trackmap/", views.Trackmap.as_view(), name="trackmap"),
    # path(
    #     "heritage_sites/", views.HeritageSiteListView.as_view(), name="heritage_sites"
    # ),
    # path(
    #     "heritage_site/<int:heritage_site_id>/",
    #     views.heritage_site,
    #     name="heritage_site",
    # ),
    path("visits/", views.VisitListView.as_view(), name="visits"),
    path("visit/<int:visit_id>/", views.visit, name="visit"),

]

storymaps/urls.py
from django.urls import path
from . import views

app_name = "storymaps"

urlpatterns = [
    path("storymaps/", views.storymaps, name="storymaps"),
    path("timelines/", views.timelines, name="timelines"),
    path("carousels/", views.carousels, name="carousels"),
    path("storymap/<slug:slug>/", views.storymap, name="storymap"),
    path("timeline/<slug:slug>/", views.timeline, name="timeline"),
    path("carousel/<slug:slug>/", views.carousel, name="carousel"),
]

locations/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.gis.geos import GEOSGeometry
from django.contrib.contenttypes.fields import GenericRelation, GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from notes.models import *
from companies.models import Company
from utils.utils import custom_slugify

import json

if settings.GDAL_INSTALLED:
    from django.contrib.gis.db.models import GeometryField, PointField

    geometry_fieldtype = GeometryField
    location_geometry_fieldtype = PointField
else:
    geometry_fieldtype = models.TextField
    location_geometry_fieldtype = models.TextField


class UKArea(models.Model):
    ITL121CD = models.CharField(max_length=10)
    ITL121NM = models.CharField(max_length=255)
    BNG_E = models.FloatField()
    BNG_N = models.FloatField()
    LONG = models.FloatField()
    LAT = models.FloatField()
    geometry = geometry_fieldtype(blank=True, null=True)

    # Bounding box fields
    bbox_longitude_min = models.FloatField(default=0.0)
    bbox_latitude_min = models.FloatField(default=0.0)
    bbox_longitude_max = models.FloatField(default=0.0)
    bbox_latitude_max = models.FloatField(default=0.0)

    def save(self, *args, **kwargs):
        # Calculate bounding box
        self.calculate_bounding_box()
        super().save(*args, **kwargs)

    def _reset_bounding_box(self):
        """Reset bounding box to default values."""
        self.bbox_longitude_min = 0.0
        self.bbox_latitude_min = 0.0
        self.bbox_longitude_max = 0.0
        self.bbox_latitude_max = 0.0

    def calculate_bounding_box(self):
        try:
            if self.geometry:
                bbox = self.geometry.extent
                (
                    self.bbox_longitude_min,
                    self.bbox_latitude_min,
                    self.bbox_longitude_max,
                    self.bbox_latitude_max,
                ) = bbox
            else:
                self._reset_bounding_box()
        except Exception as e:
            print(f"Error calculating bounding box: {e}")
            self._reset_bounding_box()

    def __str__(self):
        return self.ITL121NM


class ELR(models.Model):
    slug = models.SlugField(
        default=None,
        null=True,
        blank=True,
        max_length=255,
        unique=True,
        help_text="Enter a slug only if you wish to override that which will be autogenerated",
    )
    item = models.SlugField(max_length=20, blank=True, default="")
    itemLabel = models.CharField(max_length=400, blank=True, default="")
    itemAltLabel = models.CharField(max_length=200, blank=True, default="")
    geojson = models.JSONField(blank=True, default=None, null=True)
    geometry = geometry_fieldtype(blank=True, null=True, default=None, srid=4326)
    start_point = models.ForeignKey(
        "Location",
        on_delete=models.CASCADE,
        related_name="elr_start_points",
        default=None,
        null=True,
    )
    end_point = models.ForeignKey(
        "Location",
        on_delete=models.CASCADE,
        related_name="elr_end_points",
        default=None,
        null=True,
    )
    min_lat = models.FloatField(blank=True, null=True, default=None)
    min_lon = models.FloatField(blank=True, null=True, default=None)
    max_lat = models.FloatField(blank=True, null=True, default=None)
    max_lon = models.FloatField(blank=True, null=True, default=None)
    length = models.FloatField(blank=True, null=True, default=None)
    derived = models.BooleanField(default=False)
    note = models.CharField(max_length=200, blank=True, default="")

    owneroperators = models.ManyToManyField(Company, blank=True)

    references = models.ManyToManyField(
        Reference, related_name="elr_references", blank=True
    )

    events = GenericRelation(
        "locations.LocationHistoricEvent", related_query_name="elr"
    )

    def get_absolute_url(self):
        return reverse("locations:elr_map", kwargs={"slug": self.slug})

    def __str__(self):
        return f"{self.itemAltLabel} {self.itemLabel}" or ""

    @property
    def display_name(self):
        return f"{self.itemAltLabel} {self.itemLabel}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.itemLabel).replace("-", "_")

        if self.geojson and not self.geometry:
            geom_json = self.geojson["features"][0]["geometry"]
            self.geometry = GEOSGeometry(json.dumps(geom_json), srid=4326)
        super().save(*args, **kwargs)


class LocationCategory(models.Model):
    category = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.category

    class Meta:
        verbose_name = "Location Category"
        verbose_name_plural = "Location Categories"
        managed = True


class Location(models.Model):
    slug = models.CharField(
        max_length=255,
        default=None,
        blank=True,
        null=True,
    )
    wikiname = models.CharField(max_length=200, blank=True, null=True)
    wikislug = models.CharField(max_length=250, default=None, blank=True, null=True)
    wikidata_id = models.CharField(max_length=20, default=None, blank=True, null=True)
    wikidata = models.CharField(max_length=20, default=None, blank=True, null=True)
    wiki_altnames = models.CharField(max_length=200, blank=True, null=True)
    notes = models.TextField(default=None, blank=True, null=True)
    postcode = models.CharField(default=None, blank=True, null=True, max_length=10)
    disused_stations_slug = models.CharField(max_length=200, blank=True, null=True)
    geometry = geometry_fieldtype(blank=True, null=True, default=None)
    atcocode = models.CharField(max_length=20, blank=True, null=True)
    tiploccode = models.CharField(max_length=20, blank=True, null=True)
    crscode = models.CharField(max_length=10, blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    namealt = models.CharField(max_length=100, blank=True, null=True)
    easting = models.FloatField(blank=True, null=True)
    northing = models.FloatField(blank=True, null=True)
    osm_node = models.CharField(max_length=20, blank=True, null=True)
    media_caption = models.CharField(max_length=100, blank=True, null=True)
    media_credit = models.CharField(max_length=200, blank=True, null=True)
    media_url = models.URLField(blank=True, null=True, max_length=400)

    RCH_StopsGB_PlaceId = models.CharField(max_length=20, blank=True, null=True)
    RCH_StopsGB_StationId = models.CharField(max_length=20, blank=True, null=True)
    RCH_StopsGB_Place = models.CharField(max_length=100, blank=True, null=True)
    RCH_StopsGB_AbbrStation = models.CharField(max_length=50, blank=True, null=True)
    RCH_StopsGB_Station = models.CharField(max_length=100, blank=True, null=True)
    RCH_StopsGB_Altnames = models.CharField(max_length=200, blank=True, null=True)
    RCH_StopsGB_Predicted_Place = models.CharField(
        max_length=100, blank=True, null=True
    )

    SOURCE_TYPE = (
        (1, "Wikipedia"),
        (2, "Custom"),
    )
    source = models.IntegerField(choices=SOURCE_TYPE, default=1)

    references = models.ManyToManyField(
        Reference, related_name="locations_references", blank=True
    )

    owner_operators = models.ManyToManyField(
        Company, related_name="locations_owned_or_operated", blank=True
    )

    categories = models.ManyToManyField(
        LocationCategory, related_name="locations_in_category", blank=True
    )

    posts = models.ManyToManyField(Post, related_name="location_posts", blank=True)

    elrs = models.ManyToManyField(
        ELR, through="ELRLocation", related_name="locations_on_elr", blank=True
    )

    """
    GenericRelation is a virtual reverse relation (no DB column, so no migration).
    It is not strictly necessary for the relationship to work but it makes queries, prefetches and attribute access such as via 'location.events.all()' convenient and efficient, and enables using the inline on the model admin more naturally.
    """
    events = GenericRelation(
        "locations.LocationHistoricEvent", related_query_name="location"
    )

    def get_absolute_url(self):
        # Enables "View on Site" link in Admin to go to detail view on (non-admin) site
        return reverse("locations:location", kwargs={"slug": self.slug})

    def __str__(self):
        return self.wikiname or self.name or str(self.id)

    def save(self, *args, **kwargs):
        if self.wikislug:
            self.slug = custom_slugify(self.wikislug)
        elif self.name:
            self.slug = custom_slugify(self.name)

        # if self.geometry:
        #     coords = self.geometry
        #     self.latitude, self.longitude = coords

        super().save(*args, **kwargs)

    @property
    def display_name(self):
        return self.name or self.wikiname or f"OpenStreetMaps node {self.osm_node}"

    class Meta:
        managed = True


class LocationCode(models.Model):
    location_fk = models.ForeignKey(Location, on_delete=models.CASCADE)
    location_code = models.CharField(max_length=200, blank=True, null=True)
    from_date = models.CharField(max_length=200, blank=True, null=True)
    to_date = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return f" {self.location_fk.name} {self.location_code}"

    class Meta:
        verbose_name = "Location Code"
        verbose_name_plural = "Location Codes"


class RouteCategory(models.Model):
    category = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.category

    class Meta:
        verbose_name = "Route Category"
        verbose_name_plural = "Route Categories"
        managed = True


class RouteMap(models.Model):
    # In Wikipedia, a Routemap can appear on more than one Route page.
    SOURCE_TYPE = (
        (1, "Wikipedia"),

storymaps/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import *


class SlideAdminForm(forms.ModelForm):

    class Meta:
        model = Slide
        fields = "__all__"

        widgets = {
            "notes": TinyMCE(
                attrs={"class": "form-control tinymce-editor", "cols": 80, "rows": 30},
                mce_attrs={
                    "content_style": """
                        body {
                            margin: 8px;
                            font-size: 13px;
                        }

                        p {
                            margin: 0 0 0.75em 0;
                        }
                    """,
                    "content_css": [
                        "/static/css/bootstrap.min.css",
                        "/static/css/custom-styles.css",
                    ],
                },
            ),
        }

locations/templates/locations/depots_vis_timeline.html
<!doctype html>
<html>
  <head>
    <title>Timeline</title>
  </head>

  <body>
    <div id="visualization"></div>

    <script type="text/javascript">
      var container = document.getElementById('visualization');
      var jsonObject = JSON.parse('{{ timeline_json | escapejs }}');
      var items = new vis.DataSet(jsonObject);
      var options = {orientation: 'top'};
      var timeline = new vis.Timeline(container, items, options);
    </script>
  </body>
</html>

locations/templates/locations/folium_historymap.html
{% extends "../mainmenu/base.html" %}

{% block header %}{{map.header.render|safe}}{% endblock header %}
{% block content_title %}{{title}}{% endblock %}
{% block content %}
  {% if map %}
    {{map.html.render|safe}}
    <script>{{map.script.render|safe}}</script>
  {% else %}
    <h4>No co-ordinate data available for this selection to generate the map</h4>
  {% endif %}
 
{% endblock %}

locations/templates/locations/heritage_site.html
{% extends "../mainmenu/base.html" %}

{% block content_title %}{{ heritage_site }}{% endblock %}
{% block content_desc %}{% endblock %}

{% block content %}
  
    <div class="panel panel-default">
      <div class="panel-heading">
      </div>
      <div class="panel-body">
        Type: {{ heritage_site.tpam_type }}
        ; {{ heritage_site.type }}
        <br>
        Country: {{ heritage_site.country }}
        <br>
        Notes: {{ heritage_site.notes|linebreaks|safe }}
      </div>
    </div> <!-- panel -->

{% endblock content %}

locations/templates/locations/index.html
{% extends "../mainmenu/base.html" %}

{% block content_title %}Locations Menu{% endblock %}
{% block content_desc %}{% endblock %}
{% block content %}

    <div class="bd-example">
        <ul class="list-group">
            <a class="list-group-item list-group-item-action list-group-item-primary" href="{% url 'locations:locations' %}">Locations</a>    
            <a class="list-group-item list-group-item-action list-group-item-primary" href="{% url 'locations:routes' %}">Routes</a>
            <a class="list-group-item list-group-item-action list-group-item-primary" href="{% url 'locations:routes_southern' %}">Southern Railway Routes</a>
            <a class="list-group-item list-group-item-action list-group-item-primary" href="{% url 'locations:elrs' %}">ELRs</a>
            <a class="list-group-item list-group-item-action list-group-item-primary" href="{% url 'locations:regional_map_select' %}">Regional Railway Map</a>

            {% comment %}
            <a class="list-group-item list-group-item-action list-group-item-primary" href="{% url 'locations:heritage_sites' %}">Museums & Heritage Sites </a>

            <a class="list-group-item list-group-item-action list-group-item-primary" href="{% url 'locations:visits' %}">Heritage Site Visits</a>
            <a class="list-group-item list-group-item-action list-group-item-primary" href="{% url 'locations:trackmap' %}">Track Diagrams</a>
            <a class="list-group-item list-group-item-action list-group-item-primary" href="{% url 'locations:regional_map_select' %}">Closed Lines Map</a>

            <a class="list-group-item list-group-item-action list-group-item-primary" href="{% url 'locations:location_timeline' %}">Location Timeline</a>
            {% endcomment %}
        </ul>
    </div>
{% endblock %}

locations/templates/locations/lists.html
{% extends "../mainmenu/base.html" %}
{% load custom_filters %}

{% block title %}{{object_type}}{% endblock %}

{% block content %}
  <div class="container-fluid">

    <div class="row">
      <div class="col-md-4">
        <h1 class="text-primary text-center">{{object_type}}</h1>
      </div>

      <div class="col-md-8">
        <div class="text-left">
          <form method="POST" action="" enctype="multipart/form-data" class="mx-auto">
            {% csrf_token %}
            {{ selection_criteria }}
            <input type="submit" class="btn btn-primary" name="submit_input" value="Submit" />
          </form>
        </div>
      </div>
    </div>

    {% if not queryset.object_list %}
    <div class="row">
      <div class="col-12">
        <div class="alert alert-success" role="alert">
          No {{object_type}} Found for those Search Criteria
        </div>
      </div>
    </div>

    {% else %}

      {% with col1=queryset.object_list|slice:":20" col2=queryset.object_list|slice:"20:40" col3=queryset.object_list|slice:"40:" %}

      <div class="container mb-1">
        <div class="row">

          <div class="col-md-4">
            {% for object in col1 %}
              <div>
                <a href="{% url url_name object.id %}" class="d-block text-truncate" style="max-width: 100%;">
                  {{ object.display_name }}
                </a>
              </div>
            {% endfor %}
          </div>

          <div class="col-md-4">
            {% for object in col2 %}
              <div>
                <a href="{% url url_name object.id %}" class="d-block text-truncate" style="max-width: 100%;">
                  {{ object.display_name }}
                </a>
              </div>
            {% endfor %}
          </div>

          <div class="col-md-4">
            {% for object in col3 %}
              <div>
                <a href="{% url url_name object.id %}" class="d-block text-truncate" style="max-width: 100%;">
                  {{ object.display_name }}
                </a>
              </div>
            {% endfor %}
          </div>

        </div>
      </div> <!-- End of container -->
      {% endwith %}
    {% endif %}
  </div><!-- End of Container -->

{% include "mainmenu/pagination.html" with page=queryset %}  
{% endblock content %}

locations/templates/locations/map_closed_lines_select.html
{% extends "mainmenu\base.html" %}
{% block title %}Routes Mapping{% endblock %}
{% block header %}{% load django_bootstrap5 %}{% endblock %}
{% block content_title %}Choose a County (Administrative Area){% endblock %}
{% block content_desc %}{% endblock %}
{% block content %}
  <form method='POST' action="">
      {% csrf_token %}
      {{location_list}}
      <p></p><p></p>
      {% bootstrap_button "Generate Map" button_type="submit" button_class="btn-primary" %}
  </form>
{% endblock content %}

locations/templates/locations/route.html
{% extends "../mainmenu/base.html" %}

{% block head %}
{% endblock head %}

{% block content %}
  <h1 class="text-primary text-center mt-3">{{ route }}</h1>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12 col-lg-12">

        <!-- Tab navigation -->
        <ul class="nav nav-tabs" id="myTab" role="tablist">

          {% if route.notes %}
            <li class="nav-item">
              <a class="nav-link {% if route.notes %}active text-primary bg-white{% else %}text-white bg-primary{% endif %}" id="notes-tab" data-bs-toggle="tab" href="#notes" role="tab" aria-controls="notes" aria-selected="false">Notes</a>
            </li>
          {% endif %}

          {% if route.wikipedia_slug %}
            <li class="nav-item">
              <a class="nav-link {% if not route.notes %}active text-primary bg-white{% else %}text-white bg-primary{% endif %}" id="wikipedia-tab" data-bs-toggle="tab" href="#wikipedia" role="tab" aria-controls="wikipedia" aria-selected="false">Wikipedia</a>
            </li>
          {% endif %}
          
          {% if route.wikipedia_routemaps %}
            <li class="nav-item">
              <a class="nav-link text-white bg-primary" href="{% url 'locations:route_storymap' route.slug %}">Route Description</a>
            </li>
          {% endif %}

          {% if timeline_json %}
            <li class="nav-item">
              <a class="nav-link text-white bg-primary" id="timeline-tab" data-bs-toggle="tab" href="#timeline" role="tab" aria-controls="timeline" aria-selected="false">Timeline</a>
            </li>
          {% endif %}
          
          {% if references %}
            <li class="nav-item">
              <a class="nav-link text-white bg-primary" id="references-tab" data-bs-toggle="tab" href="#references" role="tab" aria-controls="references" aria-selected="false">References</a>
            </li>
          {% endif %}

          {% if route.wikipedia_routemaps or elrs %}
            <li class="nav-item text-white">
              <a class="nav-link text-white bg-primary" href="{% url 'locations:route_map' route.slug %}">Map</a>
            </li>
          {% endif %}

          {% if route.wikipedia_routemaps or elrs %}
            <li class="nav-item text-white">
              <a class="nav-link text-white bg-primary" href="{% url 'locations:route_timeline' route.slug %}">Timeline Map</a>
            </li>
          {% endif %}
        </ul>

        <!-- Tab content -->
        <div class="tab-content" id="myTabContent">

          {% if route.notes %}
            <div class="tab-pane fade show active mt-4" id="notes" role="tabpanel" aria-labelledby="notes-tab">
              {% autoescape off %}
              {{ route.notes }}
              {% endautoescape %}
            </div>
          {% endif %}

          {% if route.wikipedia_slug %}
            <div class="tab-pane fade {% if not route.notes %}show active{% endif %}" id="wikipedia" role="tabpanel" aria-labelledby="wikipedia-tab">
              <iframe src='https://en.wikipedia.org/wiki/{{route.wikipedia_slug}}' id="NLSiframe" width="100%" height="700" marginwidth="300">
                <p>Your browser does not support iframes - open map using 'Open Popup' on left</p>
              </iframe>
            </div>
          {% endif %}

          {% if timeline_json %}
            <div class="tab-pane fade" id="timeline" role="tabpanel" aria-labelledby="timeline-tab">
              <div id="visualization">
                <script type="text/javascript">
                  var container = document.getElementById('visualization');
                  var jsonObject = JSON.parse('{{ timeline_json | safe | escapejs }}');
                  var items = new vis.DataSet(jsonObject);
                  var options = {orientation: 'top', type: 'point'};
                  var timeline = new vis.Timeline(container, items, options);
                </script>
              </div>
            </div>
          {% endif %}

          {% if references %}
            <div class="tab-pane fade mt-4" id="references" role="tabpanel" aria-labelledby="references-tab">
                {% for reference in references %}
                
                  {% if '/ukla/' in reference.url %}
                    <h3><a href="https://www.legislation.gov.uk{{reference.url}}">{{ reference.full_reference }}</a></h3>
                  {% elif reference.url %}
                    <h3><a href="{{reference.url}}">{{ reference.full_reference }}</a></h3>
                  {% else %}
                    <h3>{{reference.full_reference}}</h3>
                  {% endif %}

                  {% if reference.description %}
                    {{reference.description|safe}}
                  {% endif %}

                {% endfor %}
            </div>
          {% endif %}

          {% if route.wikipedia_routemaps or elrs %}
            <div class="tab-pane fade" id="maps" role="tabpanel" aria-labelledby="maps-tab">
              <div class="container">
                <div class="row justify-content-center align-items-center">
                    <div class="col-12">
                      {% if map %}
                        {{map|safe}}
                      <script script>{{map.script.render|safe}}</script>
                      {% else %}
                        <h4>No map available for this route</h4>
                      {% endif %}
                    </div>
                </div>
            
                {% if elrs %}
                  <h2>Engineering Line References covered by this route:-</h2>
                  {% for elr in elrs %}
                    <h4>{{elr.itemAltLabel}} {{elr.itemLabel}}</h4>
                  {% endfor %}
                {% endif %}
            </div>
          {% endif %}

          {% if route.wikipedia_routemaps or elrs %}
            <div class="tab-pane fade" id="timeline-map" role="tabpanel" aria-labelledby="timeline-map">
              <div class="container">
                <div class="row justify-content-center align-items-center">
                    <div class="col-12">
                      {% if map %}
                        {{map|safe}}
                      <script script>{{map.script.render|safe}}</script>
                      {% else %}
                        <h4>No map available for this route</h4>
                      {% endif %}
                    </div>
                </div>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var tabLinks = document.querySelectorAll('a[data-bs-toggle="tab"]');

    tabLinks.forEach(function(link) {
      link.addEventListener('shown.bs.tab', function(event) {
        // Remove active classes from all tab links
        tabLinks.forEach(function(link) {
          link.classList.remove('text-primary', 'bg-white');
          link.classList.add('text-white', 'bg-primary');
        });

        // Add active classes to the newly activated tab link
        event.target.classList.add('text-primary', 'bg-white');
        event.target.classList.remove('text-white', 'bg-primary');
      });
    });

    // Highlight the initially active tab link
    var initialActiveTabLink = document.querySelector('.nav-link.active');
    if (initialActiveTabLink) {
      initialActiveTabLink.classList.add('text-primary', 'bg-white');
      initialActiveTabLink.classList.remove('text-white', 'bg-primary');
    }
  });
</script>

{% endblock %}

locations/templates/locations/visit_list.html
{% extends "../mainmenu/base.html" %}

{% block content_title %}Heritage Site Visits{% endblock %}
{% block content_desc %}{% endblock %}

{% block content %}

  <ul>
    {% for visit in object_list %}
      <li>
        <h3>{{ visit.location }} on {{ visit.date }}
        <a href="{% url 'notes:visit' visit.id %}"><i class="fa fa-solid fa-camera"></i></a>
        </h3>
        {% autoescape off %}
        {{ visit.notes|linebreaks }}
        {% endautoescape %}
      </li>
    {% empty %}
      <li>No Visits have been added yet.</li>
    {% endfor %}
  </ul>

{% endblock content %}