TPAM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from TPAM.admin import CustomAdminSite

admin.site.__class__ = CustomAdminSite

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("", include("mainmenu.urls", namespace="mainmenu")),
    path("api/", include("api.urls", namespace="api")),
    path("users/", include("users.urls", namespace="users")),
    path("rtt/", include("rtt.urls", namespace="rtt")),
    path("locos/", include("locos.urls", namespace="locos")),
    path("companies/", include("companies.urls", namespace="companies")),
    path("notes/", include("notes.urls", namespace="notes")),
    path("brmsra/", include("brmsra.urls", namespace="brmsra")),
    path("people/", include("people.urls", namespace="people")),
    path("storymaps/", include("storymaps.urls", namespace="storymaps")),
    path("locations/", include("locations.urls", namespace="locations")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    SHOW_TOOLBAR_CALLBACK = True

api/urls.py
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'api'

urlpatterns = [
    path('register/', views.register),
    path('login/', views.login),
    # path('manufacturers/', views.Manufacturers.as_view(), name='manufacturers'),
    path('manufacturers/', views.manufacturers, name='manufacturers'),
    path('manufacturer/<int:pk>', views.manufacturer, name='manufacturer'),
    path('persons/', views.persons, name='persons'),
    ]

# To investigate:- Appears in https://www.django-rest-framework.org/tutorial/3-class-based-views/
# urlpatterns = format_suffix_patterns(urlpatterns)

locos/urls.py
from django.urls import path
from . import views

app_name = "locos"

urlpatterns = [
    path("", views.index, name="index"),
    path("loco_classes/", views.loco_classes, name="loco_classes"),
    path("loco_classes/<slug>/", views.loco_class, name="loco_class"),
    path("locomotives/", views.locomotives, name="locomotives"),
    path("locomotive/<int:locomotive_id>/", views.locomotive, name="locomotive"),
    path("photos/", views.photos, name="photos"),
    path("photo/<int:photo_id>/", views.photo, name="photo"),
]

mainmenu/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'mainmenu'

urlpatterns = [
    path('', views.index, name='index'),
]

notes/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = "notes"

urlpatterns = [
    path("", views.index, name="index"),
    path("posts/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"),
    path("posts/", views.post_list, name="post_list"),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("references/", views.references, name="references"),
    path("reference/<int:reference_id>/", views.reference, name="reference"),
    path("timeline", views.timeline, name="timeline"),
]

rtt/urls.py
from django.urls import path
from . import views

app_name = 'rtt'
urlpatterns = [
    path('', views.locations, name='locations'),
    path('times/<str:crscode>/', views.times, name='times'),
    path('livefreight/<str:crscode>/', views.livefreight, name='livefreight'),
    path('livepassenger/<str:crscode>/', views.livepassenger, name='livepassenger'),
    path('service/<str:uid>/', views.service, name='service'),
    path('locations/', views.locations, name='locations'),
    path('location/<str:crscode>/', views.location, name='location'),
]

users/urls.py
from datetime import datetime
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import forms, views


app_name = "users"
urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="users/login.html",
            authentication_form=forms.BootstrapAuthenticationForm,
            extra_context={
                "title": "Log in",
                "year": datetime.now().year,
            },
        ),
        name="login",
    ),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("register/", views.register, name="register"),
]

mainmenu/models.py
from django.db import models
from django.contrib.auth.models import User


class MyDjangoApp(models.Model):
    image = models.ImageField(upload_to='media/')
    summary = models.TextField()
    url = models.SlugField()
    order = models.IntegerField()

    def __str__(self):
        return self.summary


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    avatar = models.ImageField(default='avatar.png', upload_to='avatars')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"profile of the user {self.user.username}"

mainmenu/views.py
from django.shortcuts import render
from .models import MyDjangoApp
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator


def index(request):
    mydjangoapps = MyDjangoApp.objects.all().order_by("order")
    return render(request, "mainmenu/index.html", {"mydjangoapps": mydjangoapps})


def pagination(request, queryset, instances=40):
    paginator = Paginator(queryset, instances)
    page = request.GET.get("page")

    try:
        paginated_queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver the first page
        paginated_queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver the last page of results
        paginated_queryset = paginator.page(paginator.num_pages)

    return paginated_queryset

mainmenu/templates/mainmenu/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Up and Down The Line{% endblock title %}</title>

    {% load django_bootstrap5 %}
    {% load static %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <!-- /* Bootstrap CSS not required as loaded in SASS CSS (/css/style.css file generated from SASS) -->

    <link rel="stylesheet" href="{% static 'css/fontawesome_custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom-styles.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat|Raleway&display=swap">
    <link rel="stylesheet" type="text/css" href="https://en.wikipedia.org/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022">

    <script type="text/javascript" src="https://unpkg.com/vis-timeline@latest/standalone/umd/vis-timeline-graph2d.min.js"></script>
    <link href="https://unpkg.com/vis-timeline@latest/styles/vis-timeline-graph2d.min.css" rel="stylesheet" type="text/css" />

    {% block head %}{% endblock %}
  </head>
  
  <body>  

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary flex-md-nowrap p-0 shadow fixed-top">

      <a class="navbar-brand me-0 px-3" href="{% url 'mainmenu:index' %}">Home</a>

      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarToggler">
        <ul class="navbar-nav me-auto">

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownMotivePower" role="button" data-bs-toggle="dropdown" aria-expanded="false">Rolling Stock</a>
            <div class="dropdown-menu bg-primary" aria-labelledby="dropdownMotivePower">
              <a class="dropdown-item nav-link" href="{% url 'locos:loco_classes' %}">Locomotive Classes</a>
              <a class="dropdown-item nav-link" href="{% url 'locos:locomotives' %}">Locomotives</a>
              <a class="dropdown-item nav-link" href="{% url 'locos:photos' %}">Photo Album</a>
            </div>
          </li>
    
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownPeople" role="button" data-bs-toggle="dropdown" aria-expanded="false">People</a>
            <div class="dropdown-menu bg-primary" aria-labelledby="dropdownPeople">
              <a class="dropdown-item nav-link" href="{% url 'people:people' %}">Famous People</a>
              <a class="dropdown-item nav-link" href="{% url 'people:people_storyline' %}">People Storyline</a>
              <a class="dropdown-item nav-link" href="{% url 'people:people_vis_timeline' %}">People Timeline</a>
            </div>
          </li>
    
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownLocations" role="button" data-bs-toggle="dropdown" aria-expanded="false">Locations</a>
            <div class="dropdown-menu bg-primary" aria-labelledby="dropdownLocations">
              <a class="dropdown-item nav-link" href="{% url 'locations:locations' %}">Locations</a>
              <a class="dropdown-item nav-link" href="{% url 'locations:routes' %}">Routes</a>
              <a class="dropdown-item nav-link" href="{% url 'locations:routes_southern' %}">Southern Railway Routes</a>
              <a class="dropdown-item nav-link" href="{% url 'locations:elrs' %}">Engineers Line References</a>              
              <a class="dropdown-item nav-link" href="{% url 'locations:regional_map_select' %}">Regional Railmap</a>
            </div>
          </li>
    
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownCompanies" role="button" data-bs-toggle="dropdown" aria-expanded="false">Companies</a>
            <div class="dropdown-menu bg-primary" aria-labelledby="dropdownCompanies">
              <a class="dropdown-item nav-link" href="{% url 'companies:manufacturers' %}">Manufacturers</a>
              <a class="dropdown-item nav-link" href="{% url 'companies:companies' %}">Owner Operators</a>
            </div>
          </li>
    
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownNotes" role="button" data-bs-toggle="dropdown" aria-expanded="false">Reference</a>
            <div class="dropdown-menu bg-primary" aria-labelledby="dropdownNotes">
              <a class="dropdown-item nav-link" href="{% url 'notes:post_list' %}">Notes</a>
              <a class="dropdown-item nav-link" href="{% url 'notes:references' %}">References</a>
              <a class="dropdown-item nav-link" href="{% url 'notes:timeline' %}">Railway Timeline</a>
              <a class="dropdown-item nav-link" href="{% url 'storymaps:timelines' %}">StoryTimelines</a>
              <a class="dropdown-item nav-link" href="{% url 'storymaps:storymaps' %}">Storymaps</a>
              <a class="dropdown-item nav-link" href="{% url 'storymaps:carousels' %}">Storyboards</a>
            </div>
          </li>
    
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownLTT" role="button" data-bs-toggle="dropdown" aria-expanded="false">Live Train Times</a>
            <div class="dropdown-menu bg-primary" aria-labelledby="dropdownLTT">
              <a class="dropdown-item nav-link" href="{% url 'rtt:locations' %}">Live Train Times</a>
            </div>
          </li>
        </ul>
     

      <div class="d-flex ms-auto navbar-nav">    
        {% if user.is_authenticated %}
          <div class="nav-item text-nowrap">  
            <a class="nav-link px-3">Hello {{ user.username }}</a>
          </div>
          <div class="nav-item text-nowrap">
            <form action="{% url 'users:logout' %}" method="post" class="d-inline">
              {% csrf_token %}
              <button type="submit" class="nav-link btn btn-link px-3">Logout</button>
            </form>
          </div>
        {% else %}
          <div class="nav-item text-nowrap"> 
            <a class="nav-link ms-auto px-3" href="{% url 'users:register' %}">Register</a>
          </div>
          <div class="nav-item text-nowrap"> 
            <a class="nav-link px-3" href="{% url 'users:login' %}">Login</a>
          </div>
        {% endif %}
      </div>      
    </div> 

    </nav>



    <main class="position-relative container ms-sm-auto">

    {% block header %}{% endblock %}

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning alert-dismissible" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">             
            </button>
          </div>
        {% endfor %}
      {% endif %}

      {% block content %}
      {% endblock %}

    </main>
  </body>
</html>

mainmenu/templates/mainmenu/index copy.html
{% extends "mainmenu/base.html" %}

{% block header %}
{% endblock %}

{% block content %}
<body>
  <main>
    <section class="py-3 text-center container">
      <div class="row py-lg-3">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="text-primary">Up and Down the Line</h1>

          <p class="text-primary">The History and Geography of UK Railways and Beyond</p>
        </div>
      </div>
    </section>


    <div class="album py-4 bg-light">
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for mydjangoapp in mydjangoapps.all  %}
          <div class="col">
            <div class="card shadow-sm">
              <img src="{{ mydjangoapp.image.url }}">
              <div class="card-body">
                <p class="card-text">{{ mydjangoapp.summary }}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{{ mydjangoapp.url }}">View</a></button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>


<div class="album py-4 bg-light">
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          
          <div class="col">
            <div class="card shadow-sm">
              <img src="/media/media/HomeLocos.jpg">
              <div class="card-body">
                <p class="card-text">Rolling Stock</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'locos:loco_classes' %}">View</a></button>
                  </div>
                </div>
              </div>
            </div>
          </div><!--col-->
          
          <div class="col">
            <div class="card shadow-sm">
              <img src="/media/media/HomePeople.jpg">
              <div class="card-body">
                <p class="card-text">People</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="people">View</a></button>
                  </div>
                </div>
              </div>
            </div>
          </div><!--col-->
          
          <div class="col">
            <div class="card shadow-sm">
              <img src="/media/media/HomeMaps.jpg">
              <div class="card-body">
                <p class="card-text">Locations, Routes &amp; Maps</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="locations">View</a></button>
                  </div>
                </div>
              </div>
            </div>
          </div><!--col-->
          
          <div class="col">
            <div class="card shadow-sm">
              <img src="/media/media/HomeCompanies.jpg">
              <div class="card-body">
                <p class="card-text">Companies</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="companies">View</a></button>
                  </div>
                </div>
              </div>
            </div>
          </div><!--col-->
          
          <div class="col">
            <div class="card shadow-sm">
              <img src="/media/media/HomeTimelines_TfvYK9H.jpg">
              <div class="card-body">
                <p class="card-text">Notes and References</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="notes">View</a></button>
                  </div>
                </div>
              </div>
            </div>
          </div><!--col-->
          
          <div class="col">
            <div class="card shadow-sm">
              <img src="/media/media/HomeLiveTrains.jpg">
              <div class="card-body">
                <p class="card-text">Live Train Times</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="rtt">View</a></button>
                  </div>
                </div>
              </div>
            </div>
          </div><!--col-->
          
        </div><!--row-->
      </div><!--container-->
    </div>

  </main>

  <footer class="text-muted py-5">
    <div class="container">
      This is a non-commercial website.  Live Trains pages are under development and information provided may be inaccurate. Test sample data is sourced via <a href="https:\\www.transportapi.com">TransportAPI.com</a> which in turn sources the data as referenced <a href="https:\\www.transportapi.com/credits">here</a>.
      <p class="float-end mb-2">
        <a href="#">Back to top</a>
      </p>
    </div>
  </footer>
</body>
{% endblock %}

mainmenu/templates/mainmenu/index.html
{% extends "mainmenu/base.html" %}

{% block header %}
{% endblock %}

{% block content %}
<body>
  <main>
    <section class="py-3 text-center container">
      <div class="row py-lg-3">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="text-primary">Up and Down the Line</h1>

          <p class="text-primary">The History and Geography of UK Railways and Beyond</p>
        </div>
      </div>
    </section>


    <div class="album py-4 bg-light">
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for mydjangoapp in mydjangoapps.all  %}
          <div class="col">
            <div class="card shadow-sm">
              <img src="{{ mydjangoapp.image.url }}">
              <div class="card-body">
                <p class="card-text">{{ mydjangoapp.summary }}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{{ mydjangoapp.url }}">View</a></button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>

  </main>

  <footer class="text-muted py-5">
    <div class="container">
      This is a non-commercial website.  Live Trains pages are under development and information provided may be inaccurate. Test sample data is sourced via <a href="https:\\www.transportapi.com">TransportAPI.com</a> which in turn sources the data as referenced <a href="https:\\www.transportapi.com/credits">here</a>.
      <p class="float-end mb-2">
        <a href="#">Back to top</a>
      </p>
    </div>
  </footer>
</body>
{% endblock %}

mainmenu/templates/mainmenu/login.html
{% extends "mainmenu/base.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

mainmenu/templates/mainmenu/pagination.html
<div class="d-flex justify-content-center align-items-center">
  <div class="pagination">
    <span class="step-links">

      {% if queryset.has_previous %}
          <div class="btn-group">
            <button type="button" class="btn btn-sm btn-outline-primary"><a href="?{{ query_params }}&page={{ queryset.previous_page_number }}">Previous</a></button>
          </div> 
      {% endif %}

      <span class="current">
          Page {{ queryset.number }} of {{ queryset.paginator.num_pages }}.
      </span>

      {% if queryset.has_next %}
          <div class="btn-group">
            <button type="button" class="btn btn-sm btn-outline-primary"><a href="?{{ query_params }}&page={{ queryset.next_page_number }}">Next</a></button>
          </div> 
      {% endif %}

    </span>
  </div>
</div>