TPAM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from TPAM.admin import CustomAdminSite

admin.site.__class__ = CustomAdminSite

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("", include("mainmenu.urls", namespace="mainmenu")),
    path("api/", include("api.urls", namespace="api")),
    path("users/", include("users.urls", namespace="users")),
    path("rtt/", include("rtt.urls", namespace="rtt")),
    path("locos/", include("locos.urls", namespace="locos")),
    path("companies/", include("companies.urls", namespace="companies")),
    path("notes/", include("notes.urls", namespace="notes")),
    path("brmsra/", include("brmsra.urls", namespace="brmsra")),
    path("people/", include("people.urls", namespace="people")),
    path("storymaps/", include("storymaps.urls", namespace="storymaps")),
    path("locations/", include("locations.urls", namespace="locations")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    SHOW_TOOLBAR_CALLBACK = True

api/urls.py
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'api'

urlpatterns = [
    path('register/', views.register),
    path('login/', views.login),
    # path('manufacturers/', views.Manufacturers.as_view(), name='manufacturers'),
    path('manufacturers/', views.manufacturers, name='manufacturers'),
    path('manufacturer/<int:pk>', views.manufacturer, name='manufacturer'),
    path('persons/', views.persons, name='persons'),
    ]

# To investigate:- Appears in https://www.django-rest-framework.org/tutorial/3-class-based-views/
# urlpatterns = format_suffix_patterns(urlpatterns)

people/urls.py
from django.urls import path
from . import views

app_name = "people"

urlpatterns = [
    path("", views.index, name="index"),
    path("people/", views.people, name="people"),
    path("people_spreadsheet/", views.people_spreadsheet, name="people_spreadsheet"),
    path("person/<slug:slug>/", views.person, name="person"),
    path("people_storyline/", views.people_storyline, name="people_storyline"),
    path("people_vis_timeline/", views.people_vis_timeline, name="people_vis_timeline"),
]

people/models.py
from django.db import models
from .models import *
from notes.models import Post, Reference

import sys

sys.path.append("..")
from utils.utils import custom_slugify


class Role(models.Model):
    role = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.role

    class Meta:
        managed = True


class Person(models.Model):
    SOURCE_TYPE = (
        (1, "Wikipedia"),
        (2, "Custom"),
        (3, "South Western Railway Magazine"),
    )
    name = models.CharField(max_length=100, blank=True, default="")
    slug = models.SlugField(
        default=None,
        null=True,
        blank=True,
        max_length=255,
        unique=True,
        help_text="Enter a slug only if you wish to override that which will be autogenerated from name.",
    )
    firstname = models.CharField(max_length=100, default=None)
    surname = models.CharField(max_length=100, default=None)
    title = models.CharField(max_length=100, blank=True, null=True, default=None)
    birthdate = models.CharField(
        max_length=10,
        blank=True,
        default="",
        help_text="Format YYYY-MM-DD with only YY mandatory; Leading zeros on mmy and yy; Can use ? for any unknown digit",
    )
    birthplace = models.CharField(max_length=200, blank=True, default="")
    dieddate = models.CharField(
        max_length=10,
        blank=True,
        default="",
        help_text="Format YYYY-MM-DD with only YY mandatory; Leading zeros on mmy and yy; Can use ? for any unknown digit",
    )
    diedplace = models.CharField(max_length=200, blank=True, default="")
    nationality = models.CharField(max_length=200, blank=True, default="")
    occupation = models.CharField(max_length=200, blank=True, default="")
    wikitextslug = models.CharField(max_length=200, blank=True, default="")
    wikiimageslug = models.CharField(max_length=200, blank=True, default="")
    wikiimagetext = models.CharField(max_length=200, blank=True, default="")
    gracetextslug = models.CharField(max_length=200, blank=True, default="")
    roles = models.ManyToManyField(
        Role, through="PersonRole", related_name="persons", blank=True
    )
    posts = models.ManyToManyField(Post, related_name="person_posts", blank=True)
    references = models.ManyToManyField(Reference, blank=True)
    source = models.IntegerField(
        choices=SOURCE_TYPE,
        default=1,
    )
    date_added = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("people:person", kwargs={"person_id": self.pk})

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.name).replace("-", "_")
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "People"
        ordering = ("name",)


class PersonRole(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    date_from = models.CharField(max_length=10, blank=True, default="")
    date_to = models.CharField(max_length=10, blank=True, default="")

    def __str__(self):
        return f"{self.person} {self.role}"

    class Meta:
        verbose_name = "Person Role"
        verbose_name_plural = "People Role"

people/views.py
import json
import urllib
import markdown
import wikipediaapi
from django.db.models import Q, F
from django.shortcuts import render, redirect
from django.core.cache import cache
from django.http import QueryDict

from locos.models import LocoClass
from mainmenu.views import pagination
from .forms import *
from .models import *


def index(request):
    return render(request, "people/index.html")


def people(request):
    errors = None

    # Check if the queryset is already cached and, if not, retrieve and cache it
    queryset = cache.get("cached_queryset")
    if queryset is None:
        queryset = Person.objects.prefetch_related("references").order_by(
            "surname", "firstname"
        )
        cache.set("cached_queryset", queryset, timeout=None)  # Cache it

    # Load selection criteria from session if available, or use empty data on first load
    if request.method == "POST":
        selection_criteria = PersonSelectionForm(request.POST)
        if selection_criteria.is_valid():
            # Save criteria to session
            request.session["person_selection_criteria"] = request.POST.dict()
            return redirect(request.path_info)
    else:
        # Initialize form with session-stored data or empty if none available
        form_data = request.session.get("person_selection_criteria", None)
        selection_criteria = PersonSelectionForm(form_data)

    # Default queryset for all persons
    if selection_criteria.is_valid():
        # Build the queryset based on valid selection criteria
        queryset = people_query_build(selection_criteria.cleaned_data)
    else:
        errors = selection_criteria.errors

    queryset = pagination(request, queryset, 8)

    context = {
        "selection_criteria": selection_criteria,
        "errors": errors,
        "queryset": queryset,
    }

    return render(request, "people/people.html", context)


def people_query_build(selection_criteria):
    conditions = Q()
    cleandata = selection_criteria

    if "name" in cleandata and cleandata["name"]:
        conditions &= Q(name__icontains=cleandata["name"])

    if "role" in cleandata and cleandata["role"]:
        fk = cleandata["role"].id  # Store the role ID
        conditions &= Q(personrole__role_id=fk)

    if "source" in cleandata and cleandata["source"]:
        conditions &= Q(source=cleandata["source"])

    if "birthyear" in cleandata and cleandata["birthyear"]:
        conditions &= Q(birthdate__startswith=cleandata["birthyear"])

    if "diedyear" in cleandata and cleandata["diedyear"]:
        conditions &= Q(dieddate__startswith=cleandata["diedyear"])

    queryset = (
        Person.objects.filter(conditions)
        .prefetch_related("references")
        .order_by("surname", "firstname")
    )

    # Cache it indefinitely
    cache.set("cached_queryset", queryset, timeout=None)
    return queryset


def person(request, slug):
    person = Person.objects.get(slug=slug)
    references = Reference.objects.filter(person=person.id)
    designed_loco_classes = LocoClass.objects.filter(designer_person=person.id)

    # Get text describing the person either from a notes app research article, else Wikipedia, else none
    if person.posts.exists():
        first_post = person.posts.first()  # Get the first post in the queryset
        description_type = first_post.title
        description = first_post.body
    elif person.wikitextslug:
        wiki_wiki = wikipediaapi.Wikipedia(
            language="en",
            user_agent="github/prpfr3 TPAM",
            extract_format=wikipediaapi.ExtractFormat.HTML,
        )
        slug = urllib.parse.unquote(
            person.wikitextslug, encoding="utf-8", errors="replace"
        )
        description = wiki_wiki.page(slug).text
        description_type = "From Wikipedia:-"
    else:
        description = None
        description_type = None

    context = {
        "person": person,
        "references": references,
        "designed_loco_classes": designed_loco_classes,
        "description_type": description_type,
        "description": description,
    }
    return render(request, "people/person.html", context)


def people_spreadsheet(request):
    people = Person.objects.all()
    return render(request, "people/people_spreadsheet.html", {"people": people})


def people_storyline(request):
    errors = None
    page = None

    if request.method == "POST":
        selection_criteria = PersonTimelineSelectionForm(request.POST)

        if (
            selection_criteria.is_valid()
            and selection_criteria.cleaned_data is not None
        ):
            timeline_json = people_storyline_build(selection_criteria, request)
            return render(
                request,
                "people/people_storyline.html",
                {"timeline_json": timeline_json},
            )
        else:
            errors = selection_criteria.errors
            queryset = Person.objects.prefetch_related("references").order_by(
                "surname", "firstname"
            )

    else:
        previous_criteria = {
            "role_id": request.session.get("role_id"),
            "birthyear": request.session.get("birthyear"),
            "diedyear": request.session.get("diedyear"),
        }

        if previous_criteria["role_id"]:
            previous_criteria["role"] = Role.objects.get(
                id=previous_criteria["role_id"]
            )
        else:
            previous_criteria["role"] = None

        selection_criteria = PersonTimelineSelectionForm(
            initial=previous_criteria, clear_previous_criteria=True
        )
        queryset = Person.objects.prefetch_related("references").order_by(
            "surname", "firstname"
        )

    queryset = pagination(request, queryset)

    context = {
        "selection_criteria": selection_criteria,
        "errors": errors,
        "people": queryset,
    }

    return render(request, "people/people_storyline_selection.html", context)


def people_storyline_build(selection_criteria, request):
    conditions = Q()
    header = ""
    cleandata = selection_criteria.cleaned_data

    if "name" in cleandata and cleandata["name"]:
        conditions &= Q(name__icontains=cleandata["name"])

    if "role" in cleandata and cleandata["role"]:
        fk = cleandata["role"].id  # Store the role ID
        conditions &= Q(personrole__role_id=fk)
        header += str(cleandata["role"])

    if "birthyear" in cleandata and cleandata["birthyear"]:
        conditions &= Q(birthdate__startswith=cleandata["birthyear"])
        header += "Born In " + str(cleandata["birthyear"])

    if "diedyear" in cleandata and cleandata["diedyear"]:
        conditions &= Q(dieddate__startswith=cleandata["diedyear"])
        header += "Died In " + str(cleandata["diedyear"])

    people = (
        Person.objects.filter(conditions)
        .prefetch_related("references")
        .annotate(
            date_from=F("personrole__date_from"), date_to=F("personrole__date_to")
        )
        .order_by("surname", "firstname")
    )

    tdict = {
        "title": {
            "media": {"url": "", "caption": "", "credit": ""},
            "text": {
                "headline": "Biographies",
                "text": header,
            },
        },
        "events": [],
    }

    forlooplimiter = 0

    for person in people:
        if (person.date_from and person.date_to) or (
            person.birthdate and person.dieddate
        ):

            if (
                person.date_from and person.date_to
            ):  # i.e. the date range should be for the role rather than born/died
                start_date = person.date_from[:4]
                end_date = person.date_to[:4]
            else:
                start_date = person.birthdate[:4]
                end_date = person.dieddate[:4]

            event = {
                "media": {
                    "url": person.wikiimageslug,
                    "caption": person.wikiimagetext,
                    "credit": "Caption Credit: All credit to Wikipedia",
                },
                "start_date": {"year": start_date},
                "end_date": {"year": end_date},
                "text": {"headline": person.name, "text": ""},
            }

            html_string = markdown.markdown(
                f"https://en.wikipedia.org/wiki/{person.wikitextslug}"
            )
            event["text"]["text"] = html_string.replace('"', "'")

            pagename = person.wikitextslug.replace("_", " ")
            wiki_wiki = wikipediaapi.Wikipedia(
                language="en",
                user_agent="github/prpfr3 TPAM",
                extract_format=wikipediaapi.ExtractFormat.HTML,
            )

            if person.wikitextslug and wiki_wiki.page(person.wikitextslug).exists:
                text_array = wiki_wiki.page(person.wikitextslug).text.split(
                    "<h2>References</h2>"
                )
                event["text"] = {"text": text_array[0], "headline": pagename}
            else:
                event["text"] = {"text": html_string, "headline": pagename}

            tdict["events"].append(event)

        with open("CMEs.json", "w") as output_file:
            json.dump(tdict, output_file, indent=4)

    return json.dumps(tdict)


def people_vis_timeline(request):
    people = Person.objects.order_by("name")
    events = []
    forlooplimiter = 0

    for person in people:
        if person.birthdate and person.dieddate:
            forlooplimiter += 1
            # For format see https://visjs.github.io/vis-timeline/docs/timeline/#Data_Format
            event = {
                "id": forlooplimiter,
                "content": person.name,
                # Replace any unknown part of the date with 01 as vis_timeline requires full date
                "start": person.birthdate.replace("??", "01"),
                "end": person.dieddate.replace("??", "01"),

people/templates/people/index.html
{% extends "../mainmenu/base.html" %}

{% block content_title %}Famous Railway People{% endblock %}
{% block content_desc %}{% endblock %}

{% block content %}

  <div class="bd-example">
    <ul class="list-group">
      <li class="list-group-item list-group-item-action list-group-item-primary"><a href="{% url 'people:people' %}">Famous People</a></li>
      <li class="list-group-item list-group-item-action list-group-item-primary"><a href="{% url 'people:people_storyline' %}">People Storyline</a></li>
      <li class="list-group-item list-group-item-action list-group-item-primary"><a href="{% url 'people:people_vis_timeline' %}">People Timeline</a></li>
    </ul>
  </div>
{% endblock %}

people/templates/people/people.html
{% extends "../mainmenu/base.html" %}

{% block title %}Railway People{% endblock %}

{% block content %}
  <div class="container-fluid">

    <div class="row">
      <div class=" col-md-4 col-lg-4 col-xl-4">
        <h1 class="text-primary text-center">
          People             
          </h1>
      </div>

      <div class="col-md-8 col-lg-8 col-xl-8">
        <div class="text-left">
          <form method='POST' action="" enctype="multipart/form-data">
            <p>
            {% csrf_token %}
            <table>{{ selection_criteria }}</table>
            <input type="submit" class="btn btn-primary" name="submit_input" value="Submit">
            </p>
          </form>
        </div>
      </div>
    </div>

    {% if not queryset %}
    <div class="col-md-12">
      <div class="alert alert-success" role="alert">No Records Found for those Search Criteria</div>
    </div>
    {% else %}

      <table class="table">
        <thead>
          <tr>
            <th scope="col">Wikipedia<br>Link</th>
            <th scope="col">Grace's<br>Guide<br>Link</th>
            <th scope="col">Name</th>
            <th scope="col">Born</th>
            <th scope="col">Died</th>
            {% comment %}<th scope="col">References</th>{% endcomment %}
          </tr>
        </thead>
        <tbody>
          {% for person in queryset %}
          <tr>
              <td>
              {% if person.wikitextslug %}
                <a href="https://en.wikipedia.org//wiki/{{person.wikitextslug}}" target="_blank" rel="noopener noreferrer" class="btn btn-primary"><i class="fa fa-wikipedia-w"></i
                ></a>
              {% else %}
              N/A
              {% endif %}
              </td>
              <td>
                {% if person.gracetextslug %}
                <a href="https://gracesguide.co.uk/{{person.gracetextslug}}" class="btn btn-primary">G</i
                ></a>
                {% endif %}     
              </td>
              <td><div><a href="{% url 'people:person' person.slug %}">{{ person.name }}</a></div></td>
              <td>{{ person.birthdate}}</td>
              <td>{{ person.dieddate }}</td>
              {% comment %}
              <td>
                  {% for reference in person.references.all %}
                  <li>{{ reference }}</li>
                  {% endfor %}
              </td>
              {% endcomment %} 
          {% endfor %}
          </tr>
        </tbody>
      </table>

      {% include "mainmenu/pagination.html" with page=people %}

    {% endif %}
  </div>
  {% endblock content %}

people/templates/people/people_spreadsheet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Simple DataTable Example</title>

    <!-- DataTables CSS -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- DataTables JS -->
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
</head>
<body>

  <table id="peopleTable" class="display">
    <thead>
        <tr>
          <th scope="col">Wikipedia<br>Link</th>
          <th scope="col">Grace's<br>Guide<br>Link</th>
          <th scope="col">Name</th>
          <th scope="col">Born</th>
          <th scope="col">Died</th>
        </tr>
    </thead>
    <tbody>
        {% for person in people %}
        <tr>
          <td>
            {% if person.wikitextslug %}
              <a href="https://en.wikipedia.org//wiki/{{person.wikitextslug}}" class="btn btn-primary"><i class="fa fa-wikipedia-w"></i
              ></a>
            {% else %}
              N/A
            {% endif %}
          </td>
          <td>
            {% if person.gracetextslug %}
            <a href="https://gracesguide.co.uk/{{person.gracetextslug}}" class="btn btn-primary">G</i></a>
            {% endif %}     
          </td>
          <td><div><a href="{% url 'people:person' person.slug %}">{{ person.name }}</a></div></td>
          <td>{{ person.birthdate}}</td>
          <td>{{ person.dieddate }}</td>
        </tr>

        {% empty %}
          <h2>No Records Found.</h2>

        {% endfor %}
    </tbody>
  </table>

  <script>
    $(document).ready(function() {
        // Initialize DataTables with drop-down filters
        $('#peopleTable').DataTable({
            initComplete: function () {
                this.api().columns().every(function () {
                    var column = this;
                    var select = $('<select><option value=""></option></select>')
                        .appendTo($(column.header()))
                        .on('change', function () {
                            var val = $.fn.dataTable.util.escapeRegex(
                                $(this).val()
                            );

                            column
                                .search(val ? '^' + val + '$' : '', true, false)
                                .draw();
                        });

                    column.data().unique().sort().each(function (d, j) {
                        select.append('<option value="' + d + '">' + d + '</option>')
                    });
                });
            }
        });
    });
</script>

</body>
</html>

people/templates/people/people_spreadsheet_nonworking.html
{% extends "../mainmenu/base.html" %}

{% block head %}

    <!-- jQuery -->
    <script
    src="https://code.jquery.com/jquery-3.7.1.min.js"
    integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
    crossorigin="anonymous"></script>

    <!-- DataTables CSS -->
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/jquery.dataTables.min.css">
    
    <!-- DataTables JS -->
    <script src="https://cdn.datatables.net/2.1.8/js/jquery.dataTables.min.js"></script>
{% endblock %}

{% block title %}Railway People{% endblock %}

{% block content %}
  <div class="container-fluid">

    <div class="row">
      <div class=" col-md-4 col-lg-4 col-xl-4">
        <h1 class="text-primary text-center">People</h1>
      </div>
    </div>

    <table id="peopleTable" class="display">
      <thead>
          <tr>
            <th scope="col">Wikipedia<br>Link</th>
            <th scope="col">Grace's<br>Guide<br>Link</th>
            <th scope="col">Name</th>
            <th scope="col">Born</th>
            <th scope="col">Died</th>
          </tr>
      </thead>
      <tbody>
          {% for person in people %}
          <tr>
            <td>
              {% if person.wikitextslug %}
                <a href="https://en.wikipedia.org//wiki/{{person.wikitextslug}}" class="btn btn-primary"><i class="fa fa-wikipedia-w"></i
                ></a>
              {% else %}
                N/A
              {% endif %}
            </td>
            <td>
              {% if person.gracetextslug %}
              <a href="https://gracesguide.co.uk/{{person.gracetextslug}}" class="btn btn-primary">G</i></a>
              {% endif %}     
            </td>
            <td><div><a href="{% url 'people:person' person.slug %}">{{ person.name }}</a></div></td>
            <td>{{ person.birthdate}}</td>
            <td>{{ person.dieddate }}</td>
          </tr>

          {% empty %}
            <h2>No Records Found.</h2>

          {% endfor %}
      </tbody>
    </table>
  </div>

  <script>
    $(document).ready(function() {
        // Initialize DataTables with drop-down filters
        $('#peopleTable').DataTable({
            initComplete: function () {
                this.api().columns().every(function () {
                    var column = this;
                    var select = $('<select><option value=""></option></select>')
                        .appendTo($(column.header()))
                        .on('change', function () {
                            var val = $.fn.dataTable.util.escapeRegex(
                                $(this).val()
                            );

                            column
                                .search(val ? '^' + val + '$' : '', true, false)
                                .draw();
                        });

                    column.data().unique().sort().each(function (d, j) {
                        select.append('<option value="' + d + '">' + d + '</option>')
                    });
                });
            }
        });
    });
</script> 

{% endblock content %}

people/templates/people/people_storyline.html
{% extends "../mainmenu/base.html" %}

{% block head %}
    <!--- Created using Knightlab's Timeline. Uses the timeline JSON created in the view of the same name -->

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link title="timeline-styles" rel="stylesheet" 
        href="https://cdn.knightlab.com/libs/timeline3/latest/css/timeline.css">
    <script src="https://cdn.knightlab.com/libs/timeline3/latest/js/timeline.js"></script>

    
{% endblock %}


{% block content %}
    <div class="container-fluid">
        <div id='timeline-embed' style="width: 100%; height: 600px"></div>
    </div>

    <script>
        $(document).ready(function() {
            var embed = document.getElementById('timeline-embed');
            embed.style.height = getComputedStyle(document.body).height;
            var jsonObject = JSON.parse('{{ timeline_json | escapejs }}');
            window.timeline = new TL.Timeline('timeline-embed', jsonObject, {
                // options at https://timeline.knightlab.com/docs/options.html
                hash_bookmark: true,
                timenav_position: 'top',
                timenav_height: 250,
                scale_factor: 5
            });
            window.addEventListener('resize', function() {
                var embed = document.getElementById('timeline-embed');
                embed.style.height = getComputedStyle(document.body).height;
                timeline.updateDisplay();
            })
        });
    </script>
{% endblock content %}

people/templates/people/people_storyline_selection.html
{% extends "../mainmenu/base.html" %}

{% block content_title %}Railway People{% endblock %}
{% block content_desc %}{% endblock %}

{% block content %}
  <div class="container-fluid">

    <div class="row">
      <div class=" col-md-4 col-lg-4 col-xl-4">
        <h1 class="text-primary text-center">
          People Storyline            
          </h1>
      </div>

      <div class="col-md-8 col-lg-8 col-xl-8">
        <div class="text-left">
          <form method='POST' action="" enctype="multipart/form-data">
            <p>
            {% csrf_token %}
            <table>{{ selection_criteria }}</table>
            <input type="submit" class="btn btn-primary" name="submit_input" value="Submit">
            </p>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

people/templates/people/people_vis_timeline.html
{% extends "../mainmenu/base.html" %}

{% block head %}
  <title>Timeline</title>
{% endblock %}

{% block content %}
  <section class="container-fluid text-center py-3 mt-1">
    <div class="row">
      <div class="col-12 mx-auto">
        <h1 class="text-primary">People Timeline</h1>                      
      </div>
    </div>
  </section>

  <div id="visualization"></div>

  <script type="text/javascript">
    var container = document.getElementById('visualization');
    var jsonObject = JSON.parse('{{ timeline_json | escapejs }}');
    var items = new vis.DataSet(jsonObject);
    var options = {orientation: 'top'};
    var timeline = new vis.Timeline(container, items, options);
  </script>
{% endblock content %}

people/templates/people/person.html
{% extends "../mainmenu/base.html" %}

{% block title %}{{ person }}{% endblock %}

{% block content %}

  <h1 class="text-primary text-center">
    {{person}}
    {% if person.wikitextslug %}
      <a href="https://en.wikipedia.org//wiki/{{person.wikitextslug}}" class="btn btn-primary"><i class="fa fa-wikipedia-w"></i
      ></a>
    {% endif %}
    {% if person.gracetextslug %}
      <a href="https://gracesguide.co.uk/{{person.gracetextslug}}" class="btn btn-primary">G</i
      ></a>
    {% endif %}  
      </h1>

  <div class="panel panel-default">
    <div class="panel-body">

      <h2>
      {% if person.birthdate %}
        Born:- {{person.birthdate}}
      {% endif %}
      {% if person.birthplace %}
        at {{person.birthplace}}
      {% endif %}
      </h2>

      <h2>
      {% if person.dieddate %}
        Died:- {{person.dieddate}}
      {% endif %}
      {% if person.diedplace %}
        at {{person.diedplace}}
      {% endif %}
      </h2>

      {% if references %}
        <h2 class="text-primary">References</h2>
        {% for reference in references %}
                  
          {% if '/ukla/' in reference.url %}
            <h3><a href="https://www.legislation.gov.uk{{reference.url}}">{{ reference.full_reference }}</a></h3>
          {% elif reference.url %}
            <h3><a href="{{reference.url}}">{{ reference.full_reference }}</a></h3>
          {% else %}
            <h3>{{reference.full_reference}}</h3>
          {% endif %}

          {% if reference.description %}
            {{reference.description}}
          {% endif %}
        {% endfor %}

      {% endif %}
    
      {% if designed_loco_classes %}
        <h2 class="text-primary">Designed Loco Classes</h2>
        {% for designed_loco_class in designed_loco_classes %}
          <p>{{ designed_loco_class }}</p>
        {% empty %}
          <p>None recorded</p>
        {% endfor %}
      {% endif %}

      <h2 class="text-primary">Roles</h2>
      {% for person_role in person.personrole_set.all %}
        <p>{{ person_role.role }} 
          {% if person_role.date_from %}
            from {{ person_role.date_from }}
          {% endif %}
          {% if person_role.date_to %}
            to {{ person_role.date_to }}
          {% endif %}
        </p>
      {% empty %}
        <p>None recorded</p>
      {% endfor %}

      {% if description_type %}
        <h2 class="text-primary">{{description_type}}</h2>
        {% autoescape off %}
        <p>{{ description }}</p>
        {% endautoescape %}
      {% endif %}
    </div> <!-- panel body -->
  </div> <!-- panel -->
{% endblock content %}