TPAM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from TPAM.admin import CustomAdminSite

admin.site.__class__ = CustomAdminSite

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("", include("mainmenu.urls", namespace="mainmenu")),
    path("api/", include("api.urls", namespace="api")),
    path("users/", include("users.urls", namespace="users")),
    path("rtt/", include("rtt.urls", namespace="rtt")),
    path("locos/", include("locos.urls", namespace="locos")),
    path("companies/", include("companies.urls", namespace="companies")),
    path("notes/", include("notes.urls", namespace="notes")),
    path("brmsra/", include("brmsra.urls", namespace="brmsra")),
    path("people/", include("people.urls", namespace="people")),
    path("storymaps/", include("storymaps.urls", namespace="storymaps")),
    path("locations/", include("locations.urls", namespace="locations")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    SHOW_TOOLBAR_CALLBACK = True

api/urls.py
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'api'

urlpatterns = [
    path('register/', views.register),
    path('login/', views.login),
    # path('manufacturers/', views.Manufacturers.as_view(), name='manufacturers'),
    path('manufacturers/', views.manufacturers, name='manufacturers'),
    path('manufacturer/<int:pk>', views.manufacturer, name='manufacturer'),
    path('persons/', views.persons, name='persons'),
    ]

# To investigate:- Appears in https://www.django-rest-framework.org/tutorial/3-class-based-views/
# urlpatterns = format_suffix_patterns(urlpatterns)

locos/urls.py
from django.urls import path
from . import views

app_name = "locos"

urlpatterns = [
    path("", views.index, name="index"),
    path("loco_classes/", views.loco_classes, name="loco_classes"),
    path("loco_classes/<slug>/", views.loco_class, name="loco_class"),
    path("locomotives/", views.locomotives, name="locomotives"),
    path("locomotive/<int:locomotive_id>/", views.locomotive, name="locomotive"),
    path("photos/", views.photos, name="photos"),
    path("photo/<int:photo_id>/", views.photo, name="photo"),
]

locos/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe

from .models import *


class Select2Widget(forms.Select):
    class Media:
        css = {
            "all": (
                "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css",
            )
        }
        js = (
            "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js",
        )


class LocoClassSelectionForm(forms.ModelForm):
    designer_person = forms.ModelChoiceField(
        queryset=Person.objects.all(),
        required=False,
        widget=Select2Widget(
            attrs={"class": "search-select2", "style": "width: 200px;"}
        ),
    )

    owner_operators = forms.ModelChoiceField(
        queryset=Company.objects.order_by("name"),
        required=False,
        widget=Select2Widget(
            attrs={"class": "search-select2", "style": "width: 200px;"}
        ),
    )

    manufacturers = forms.ModelChoiceField(
        queryset=Manufacturer.objects.all(),
        required=False,
        widget=Select2Widget(
            attrs={"class": "search-select2", "style": "width: 200px;"}
        ),
    )

    wheel_arrangement = forms.ModelChoiceField(
        queryset=WheelArrangement.objects.all(),
        required=False,
        widget=Select2Widget(
            attrs={"class": "search-select2", "style": "width: 200px;"}
        ),
    )

    class Meta:
        model = LocoClass
        fields = (
            "name",
            "designer_person",
            "owner_operators",
            "manufacturers",
            "wheel_arrangement",
            "power_type",
        )

        labels = {
            "name": "Name",
            "designer_person": "Designer",
            "owner_operators": "Owner Operator",
            "manufacturers": "Manufacturer",
            "wheel_arrangement": "Wheel Arrangements",
            "power_type": "Traction Type (Steam, Diesel, Electric)",
        }


class LocomotiveSelectionForm(forms.ModelForm):
    class Meta:
        model = Locomotive
        fields = ("number_as_built",)

        widgets = {
            "number_as_built": forms.TextInput(
                attrs={
                    "style": "width: 100px",
                }
            )
        }


class LocomotiveImageForm(forms.ModelForm):
    heritage_site = forms.ModelChoiceField(
        queryset=HeritageSite.objects.order_by("name"),
        required=False,
        widget=Select2Widget(
            attrs={"class": "search-select2", "style": "width: 200px;"}
        ),
    )

    class Meta:
        model = Image
        fields = ("image_name", "heritage_site")
        labels = {"image_name": "Title", "heritage_site": "Heritage Site"}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["image_name"].required = (
            False  # For this form override the model mandatory status
        )

locos/views.py
from itertools import chain

import wikipediaapi
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Count
from django.http import QueryDict
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from notes.models import Reference
from mainmenu.views import pagination
from .forms import *
from .models import *


def index(request):
    return render(request, "locos/index.html")


def loco_classes(request):
    errors = None
    items_per_page = 30

    # Load selection criteria from session if available, or use empty data on first load
    if request.method == "POST":
        selection_criteria = LocoClassSelectionForm(request.POST)
        if selection_criteria.is_valid():
            # Save criteria to session
            request.session["loco_class_selection_criteria"] = request.POST.dict()
            return redirect(request.path_info)
    else:
        # Initialize form with session-stored data or empty if none available
        form_data = request.session.get("loco_class_selection_criteria", None)
        selection_criteria = LocoClassSelectionForm(form_data)

    # Default queryset for all loco classes
    queryset = LocoClass.objects.order_by("name")

    if selection_criteria.is_valid():
        # Build the queryset based on valid selection criteria
        queryset = loco_classes_query_build(selection_criteria.cleaned_data)
    else:
        errors = selection_criteria.errors

    queryset = pagination(request, queryset, items_per_page)

    context = {
        "selection_criteria": selection_criteria,
        "errors": errors,
        "queryset": queryset,
    }
    return render(request, "locos/motive_power_classes.html", context)


def loco_classes_query_build(selection_criteria):

    conditions = Q()
    cleandata = selection_criteria

    if "name" in cleandata and cleandata["name"]:
        conditions &= Q(name__icontains=cleandata["name"])

    if "wheel_body_type" in cleandata and cleandata["wheel_body_type"]:
        conditions &= Q(wheel_body_type__icontains=cleandata["wheel_body_type"])

    if "wheel_arrangement" in cleandata and cleandata["wheel_arrangement"]:
        fk = cleandata["wheel_arrangement"]
        conditions &= Q(wheel_arrangement_id=fk)

    if "designer_person" in cleandata and cleandata["designer_person"]:
        fk = cleandata["designer_person"]
        conditions &= Q(designer_person_id=fk)

    if "owner_operators" in cleandata and cleandata["owner_operators"]:
        fk = cleandata["owner_operators"]
        conditions &= Q(owner_operators=fk)

    if "manufacturers" in cleandata and cleandata["manufacturers"]:
        fk = cleandata["manufacturers"]
        conditions &= Q(manufacturers=fk)

    if "power_type" in cleandata and cleandata["power_type"]:
        conditions &= Q(power_type__icontains=cleandata["power_type"])

    queryset = LocoClass.objects.filter(conditions).order_by("name")
    # .annotate(total=Count("brd_class_name"))

    return queryset


def loco_class(request, slug):

    loco_class = LocoClass.objects.filter(slug=slug).order_by("name").first()

    locomotives = Locomotive.objects.filter(lococlass=loco_class.id).order_by(
        "number_as_built"
    )

    references = loco_class.references.all()
    operators = loco_class.owner_operators.all()
    manufacturers = loco_class.manufacturers.all()
    posts = loco_class.posts.all()

    context = {
        "loco_class": loco_class,
        "posts": posts,
        "locomotives": locomotives,
        "operators": operators,
        "references": references,
        "manufacturers": manufacturers,
    }

    return render(request, "locos/motive_power_class.html", context)


@login_required
def locomotives(request):
    errors = None
    # Default queryset for all locomotives
    queryset = Locomotive.objects.order_by("name")

    # Load selection criteria from session if available, or use empty data on first load
    if request.method == "POST":
        selection_criteria = LocomotiveSelectionForm(request.POST)
        if selection_criteria.is_valid():
            # Save criteria to session
            request.session["locomotive_selection_criteria"] = request.POST.dict()
            return redirect(request.path_info)
    else:
        # Initialize form with session-stored data or empty if none available
        form_data = request.session.get("locomotive_selection_criteria", None)
        selection_criteria = LocomotiveSelectionForm(form_data)

    # Filter based on selection criteria
    if (
        selection_criteria.is_valid()
        and selection_criteria.cleaned_data["number_as_built"]
    ):
        queryset = Locomotive.objects.filter(
            number_as_built__icontains=selection_criteria.cleaned_data.get(
                "number_as_built", ""
            )
        )

    queryset = pagination(request, queryset)

    context = {
        "selection_criteria": selection_criteria,
        "errors": errors,
        "queryset": queryset,
    }
    return render(request, "locos/motive_power_list.html", context)


@login_required
def locomotive(request, locomotive_id):
    lococlass = None
    operators = None
    class_designers = None
    class_designers2 = None
    class_designers3 = None
    class_manufacturers = None
    class_manufacturers2 = None
    class_manufacturers3 = None
    locomotive = Locomotive.objects.get(id=locomotive_id)
    try:
        lococlass = LocoClass.objects.get(id=locomotive.lococlass)
    except ObjectDoesNotExist:
        pass
    except Exception as e:
        print(f"{e=}")
    else:
        operators = lococlass.company_owneroperator.all()
        class_designers1 = lococlass.location_event_designer.all()
        class_designers2 = lococlass.manufacturer_designer.all()
        class_designers3 = lococlass.company_designer.all()

        class_designers = list(
            chain(class_designers1, class_designers2, class_designers3)
        )

        class_manufacturers1 = lococlass.location_event_manufacturer.all()
        class_manufacturers2 = lococlass.manufacturer_manufacturer.all()
        class_manufacturers3 = lococlass.company_manufacturer.all()

        class_manufacturers = list(
            chain(class_manufacturers1, class_manufacturers2, class_manufacturers3)
        )

    # references = Reference.objects.filter(loco=locomotive_id)

    wiki_wiki = wikipediaapi.Wikipedia(
        user_agent="github/prpfr3 TPAM",
        language="en",
        extract_format=wikipediaapi.ExtractFormat.HTML,
    )
    # The following could be introduced at a later date for where there is a Wikipedia page for a locomotive
    # page_name = locomotive.wikipedia_name.replace(' ', '_')
    # wikipedia_summary = wiki_wiki.page(page_name).text

    context = {
        "locomotive": locomotive,
        "lococlass": lococlass,
        "operators": operators,
        # 'references':references,
        "designers": class_designers,
        "manufacturers": class_manufacturers,
        # 'wikipedia_summary':wikipedia_summary,
    }

    return render(request, "locos/motive_power.html", context)


def photos(request):
    # Photos are currently not catalogued with information
    # The LocomotiveImageForm is therefore not displayed and this
    # view will display all records.
    errors = None
    queryset = Image.objects.all()

    # Load selection criteria from session if available
    if request.method == "POST":
        selection_criteria = LocomotiveImageForm(request.POST)
        if selection_criteria.is_valid():
            # Save criteria to session
            request.session["photo_selection_criteria"] = request.POST.dict()
            return redirect(request.path_info)
    else:
        # Initialize form with session-stored data or empty if none available
        form_data = request.session.get("photo_selection_criteria", None)
        selection_criteria = LocomotiveImageForm(form_data)

    # Filter queryset based on selection criteria
    if selection_criteria.is_valid():
        # queryset = Image.objects.all()
        queryset = photos_query_build(selection_criteria.cleaned_data)

    queryset = pagination(request, queryset, 27)

    context = {
        "selection_criteria": selection_criteria,
        "errors": errors,
        "queryset": queryset,
    }

    return render(request, "locos/photos.html", context)


def photos_query_build(selection_criteria):

    conditions = Q()
    cleandata = selection_criteria

    if "image_name" in cleandata and cleandata["image_name"]:
        conditions &= Q(image_name__icontains=cleandata["image_name"])

    if "heritage_site" in cleandata and cleandata["heritage_site"]:
        fk = cleandata["heritage_site"]
        conditions &= Q(location=fk)

    queryset = Image.objects.filter(conditions).order_by("image_name")
    return queryset


def photo(request, photo_id):
    photo = Image.objects.get(id=photo_id)

    context = {"photo": photo}
    return render(request, "locos/photo.html", context)

locos/templates/locos/engineer.html
{% extends "../mainmenu/base.html" %}

{% block content_title %}{{ engineer }}{% endblock %}
{% block content_desc %}{% endblock %}

{% block content %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <small>
        <a href="{% url 'locos:edit_engineer' engineer.id %}">
          Edit</a>
      </small>
    </div>
    <div class="panel-body">
      <ul>
      <li>{{ engineer.wikislug }}</li>
      <li>{{ engineer.url }}</li>
      <li>{{ engineer.notes|linebreaks }}<li/>
      </ul>
    </div>
  </div> <!-- panel -->
{% endblock content %}

locos/templates/locos/engineer_edit.html
{% extends "../mainmenu/base.html" %}

{% block header %}
  <h2>Edit:
  <a href="{% url 'locos:engineer' engineer.id %} ">{{ engineer }}</a></h2>
{% endblock header %}

{% block content %}
    
  <form action="{% url 'locos:edit_engineer' engineer.id %}" method='post'
      class="form">
      
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
    
  </form>
    
{% endblock content %}

locos/templates/locos/index.html
{% extends "../mainmenu/base.html" %}

{% block title %}Rolling Stock{% endblock %}
{% block content_title %}Rolling Stock{% endblock %}
{% block content_desc %}{% endblock %}

{% block content %}

  <div class="bd-example">
    <ul class="list-group">
      <li class="list-group-item list-group-item-action list-group-item-primary"><a href="{% url 'locos:loco_classes' %}">Locomotive Classes</a></li>
      <li class="list-group-item list-group-item-action list-group-item-primary"><a href="{% url 'locos:locomotives' %}">Locomotives</a></li>
      <li class="list-group-item list-group-item-action list-group-item-primary"><a href="{% url 'locos:photos' %}">Photo Album</a></li>
    </ul>
  </div>

{% endblock content %}

locos/templates/locos/location_select.html
{% extends "mainmenu\base.html" %}
{% block title %}Routes Mapping{% endblock %}
{% block header %}{% load django_bootstrap5 %}{% endblock %}
{% block content_title %}Choose a County (Administrative Area){% endblock %}
{% block content_desc %}{% endblock %}
{% block content %}
  <form method='POST' action="">
      {% csrf_token %}
      {{location_list}}
      <p></p><p></p>
      {% bootstrap_button "Generate Map" button_type="submit" button_class="btn-primary" %}
  </form>
{% endblock content %}

locos/templates/locos/manufacturer.html
{% extends "../mainmenu/base.html" %}

{% block content_title %}{{ builder.name }}{% endblock %}
{% block content_desc %}{% endblock %}

{% block content %}
  <div class="panel panel-default">
    <!-- Don't allow editing of builder. Use admin only.
    <div class="panel-heading">
      <small>
        <a href="{% url 'locos:edit_builder' builder.id %}">
          Edit</a>
      </small>
    </div>
  -->
    <div class="panel-body">
      <ul>
      <li>{{ builder.wikislug }}</li>
      <li>{{ builder.notes|linebreaks }}<li/>
      </ul>
    </div>
  </div> <!-- panel -->
{% endblock content %}

locos/templates/locos/motive_power.html
{% extends "../mainmenu/base.html" %}

{% block title %}{{ locomotive }}{% endblock %}

{% block content %}
  
  <div class="panel panel-default">
    <div class="panel-heading"><small></small></div>
        
    <div class="panel-body">

      <h1 class="text-primary text-center">{{locomotive}}</h1>

      {% load my_tags %}
      <ul>
      {% for key, val in locomotive|get_fields %}
        {% if val %}
          <li>{{ key }}: {{ val }}</li>
        {% endif %}
      {% endfor %}
      </ul>

      Years Since Built  {{ locomotive.age }}

      {% if lococlass %}
        <h2>Locomotive Class Details</h2>

        <ul>
          {% for key, val in lococlass|get_fields %}
            {% if val %}
              <li>{{ key }}: {{ val }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      {% endif %}

      <h2>Owners/Operators</h2>
      {% for operator in operators %}
        <li><a href="https://en.wikipedia.org//{{operator.wikislug}}">{{operator.name}}</a></li>
      {% empty %}
        <li>None recorded for this class.</li>
      {% endfor %} 

      <h2>Designer(s)</h2>
      {% for designer in designers %}
        <li><a href="https://en.wikipedia.org/{{designer.wikitextslug}}">{{designer.name}}</a></li>
      {% empty %}
        <li>None recorded for this class.</li>
      {% endfor %}

      <h2>Manufacturer(s)</h2>
      {% for manufacturer in manufacturers %}
        <li><a href="https://en.wikipedia.org/{{manufacturer.wikislug}}">{{manufacturer.name}}</a></li>
      {% empty %}
        <li>None recorded for this class.</li>
      {% endfor %}

      <h2>References</h2>
      {% for reference in references %}
        {% autoescape off %}
        <li>{{reference.full_reference}}</li>
        {% endautoescape %}
      {% empty %}
        <li>None recorded for this locomotive.</li>
      {% endfor %}

    </div> <!-- panel body -->
  </div> <!-- panel -->

{% endblock content %}

locos/templates/locos/motive_power_classes.html
{% extends "../mainmenu/base.html" %}

{% block head %}
  <style>
    .row-height {
        min-height: 38px; /* Adjust the height as needed */
    }
  </style>
{% endblock %}

{% block title %}Motive Power Classes{% endblock %}

{% block content %}
  <div class="container-fluid">

    <div class="row">
      <div class=" col-md-4 col-lg-4 col-xl-4">
        <h1 class="text-primary text-center">Loco Classes</h1>
      </div>

      <div class="col-md-4 col-lg-4 col-xl-4">
        <div class="text-left">
          <form method='POST' action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ selection_criteria }}
            <input type="submit" class="btn btn-primary" name="submit_input" value="Submit">
          </form>
        </div>
      </div>

    <div class="row">
      <div class="col-md-12 col-lg-12 col-xl-12"> 

        {% if not queryset %}
          <div class="alert alert-success" role="alert">No Classes Found for those Search Criteria</div>
        {% else %}

          {% with queryset|slice:":10" as first_third %}
          {% with queryset|slice:"10:20" as second_third %}
          {% with queryset|slice:"20:" as third_third %}

          <div class="container">       
            <div class="row">
              <div class="col-md-4">
                {% for row in first_third %}
                  <div class="row mb-1 d-flex align-items-stretch row-height">
                    <div class="col-12 d-flex align-items-left justify-content-left">
                      <a href='{% url "locos:loco_class" row.slug %}'>{{row.name}}</a>
                    </div>
                  </div>
                {% endfor %}
              </div>

              <div class="col-md-4">
                {% for row in second_third %}
                  <div class="row mb-1 d-flex align-items-stretch row-height">
                    <div class="col-12 d-flex align-items-left justify-content-left">
                      <a href='{% url "locos:loco_class" row.slug %}'>{{row.name}}</a>
                    </div>
                  </div>
                {% endfor %}
              </div>

              <div class="col-md-4">
                {% for row in third_third %}
                  <div class="row mb-1 d-flex align-items-stretch row-height">
                    <div class="col-12 d-flex align-items-left justify-content-left">
                      <a href='{% url "locos:loco_class" row.slug %}'>{{row.name}}</a>
                    </div>
                  </div>
                {% endfor %}
              </div>
            </div>

          {% endwith %}
          {% endwith %}
          {% endwith %}
          {% include "mainmenu/pagination.html" with page=queryset %} 
          </div>
        {% endif %}
      </div><!--- End of Content Columns -->
    </div><!-- End of Content Rows -->
  </div><!-- End of Container -->
{% endblock content %}

locos/templates/locos/motive_power_list.html
{% extends "../mainmenu/base.html" %}
{% block head %}
  <style>

  </style>
{% endblock %}
{% block title %}Locomotives{% endblock %}
{% block content_title %}Locomotives{% endblock %}
{% block content %}

  <div class="container-fluid">

    <div class="row">
      <div class=" col-md-4 col-lg-4 col-xl-4">
        <h1 class="text-primary text-center">Locos</h1>
      </div>

      <div class="col-md-8 col-lg-8 col-xl-8">
        <div class="text-left"> <!-- Added text-center class -->
          <form method='POST' action="" enctype="multipart/form-data">
            <p>
            {% csrf_token %}
            <div class="single-selection-container">
              {{ selection_criteria }}
              <!-- <input type="submit" class="btn btn-primary" name="submit_input" value="Submit"> -->
              <button type="submit" class="btn btn-primary">
                <i class="fas fa-search"></i> <!-- Magnifying glass icon -->
              </button>
            </div>

            </p>
          </form>
        </div>
      </div>
    </div>

    {% if not queryset %}
    <div class="col-md-12">
      <div class="alert alert-success" role="alert">No Records Found for those Search Criteria</div>
    </div>
    {% else %}

      <div class="container">
        <div class="row mb-1">
          <div class="col-3 d-flex align-items-left justify-content-left" style="font-weight: bold;">Class</div>
          <div class="col-1 d-flex align-items-left justify-content-left" style="font-weight: bold;">No. As Built</div>
        </div>

      {% for row in queryset %}
        <div class="row mb-1 d-flex align-items-stretch row-height">

          <div class="col-3 d-flex align-items-left justify-content-left">
            {% if row.lococlass %}
              {{row.lococlass}}
            {% endif %}
          </div>

          <div class="col-1 d-flex align-items-center justify-content-center">
            {% if row.number_as_built %}
              <a href="{% url 'locos:locomotive' row.id %}">{{row.number_as_built}}</a>
            {% endif %}
          </div>
        </div>
          
      {% endfor %}
      <br>
      {% include "mainmenu/pagination.html" with page=queryset %}

    {% endif %}
  </div>
{% endblock content %}

locos/templates/locos/persons_timeline.html
<!DOCTYPE html>
<html>
<head>

<!--- Created using Knightlab's Timeline. Uses the timeline JSON created in the view of the same name -->

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link title="timeline-styles" rel="stylesheet" 
      href="https://cdn.knightlab.com/libs/timeline3/latest/css/timeline.css">
<script src="https://cdn.knightlab.com/libs/timeline3/latest/js/timeline.js"></script>

<div id='timeline-embed' style="width: 100%; height: 600px"></div>
</head>

<body>
    <script>
        $(document).ready(function() {
            var embed = document.getElementById('timeline-embed');
            embed.style.height = getComputedStyle(document.body).height;
            var jsonObject = JSON.parse('{{ timeline_json | escapejs }}');
            window.timeline = new TL.Timeline('timeline-embed', jsonObject, {
                // options at https://timeline.knightlab.com/docs/options.html
                hash_bookmark: true,
                timenav_position: 'top',
                timenav_height: 250,
                scale_factor: 5
            });
            window.addEventListener('resize', function() {
                var embed = document.getElementById('timeline-embed');
                embed.style.height = getComputedStyle(document.body).height;
                timeline.updateDisplay();
            })
        });
    </script>
</body>
</html>

locos/templates/locos/persons_vis_timeline.html
<!doctype html>
<html>
  <head>
    <title>Timeline</title>
    <script type="text/javascript" src="https://unpkg.com/vis-timeline@latest/standalone/umd/vis-timeline-graph2d.min.js"></script>
    <link href="https://unpkg.com/vis-timeline@latest/styles/vis-timeline-graph2d.min.css" rel="stylesheet" type="text/css" />
    <style type="text/css">
      #visualization {
        width: 1300px;
        height: 50px;
        border: 5px solid rgb(14, 12, 26);
      }
    </style>
  </head>

  <body>
  <div id="visualization"></div>
    <script type="text/javascript">
      var container = document.getElementById('visualization');
      var jsonObject = JSON.parse('{{ timeline_json | escapejs }}');
      var items = new vis.DataSet(jsonObject);
      var options = {orientation: 'top'};
      var timeline = new vis.Timeline(container, items, options);
    </script>
  </body>
</html>

locos/templates/locos/photo.html
{% extends "../mainmenu/base.html" %}
{% load django_bootstrap5 %}

{% block content %}

  <div class="container-fluid">
    <h1 class="text-primary text-center">{{ photo.image_name }}</h1>
  </div>

  <div class="card text-center text-primary">

    <img class="card-img-top mx-auto" style="max-width:60%" src="{{ photo.image.url }}" alt="">
    <div class="card-body">

    </div><!-- card-body -->

  </div> <!-- card -->
{% endblock content %}

locos/templates/locos/photos.html
{% extends "../mainmenu/base.html" %}



{% block content %}

  <div class="container-fluid">
    <div class="row">
      <div class=" col-md-4 col-lg-4 col-xl-4">
        <h1 class="text-primary text-center">Photo Album</h1>
      </div>

      <div class="col-md-4 col-lg-4 col-xl-4">
        <div class="text-left">
          <form method='POST' action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ selection_criteria }}
            <input type="submit" class="btn btn-primary" name="submit_input" value="Submit">
          </form>
        </div>
      </div>
    </div>

    <div class="album py-4 bg-light">
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for photo in queryset  %}
            <div class="col">
              <div class="card text-center shadow-sm">
              <!-- Based on https://stackoverflow.com/questions/27229847/how-to-deal-with-portrait-image-in-bootstrap-image-grid
                -->
                
                <a style="display: block;padding-bottom: 100%;position: relative;", href="{% url 'locos:photo' photo.id %}">
                <img style="max-width: 100%;
                max-height: 100%;
                position: absolute;
                left: 0; right: 0; top: 0; bottom: 0;
                margin: auto;" src="{{ photo.image.url }}" alt=""></a>

                <div class="card-body">
                  <p class="card-text">{{photo.image_name}}</p>
                  <p class="card-text">
                    {% if photo.location %}
                        {{photo.location}}
                    {% endif %}
                    
                    {% if photo.visit %}
                      {{photo.visit}} 
                    {% endif %}
                  </p>
                  <p class="card-text">
                    {% for lococlass in photo.lococlass.all %}
                      <span><a href='{% url "locos:loco_class" lococlass.slug %}'>{{lococlass}}</a></span>
                    {% endfor %}
                  </p>
                </div>
              </div>
            </div><!--col-->
          {% endfor %}
        </div><!--row-->
      </div><!--container-->
    </div><!--album-->
  </div><!-- container fluid-->

  {% include "mainmenu/pagination.html" with page=photos %}

{% endblock content %}